### PR TITLE
need help creating conda-lock and testing dockerfile build

### PR DESCRIPTION
**Pull request by musiccabin**
can someone please help with creating conda-lock? i'm unable to do it today with the way i previously did it and how i did it in my individual milestone. it's giving me an error but i'm not understanding it.

this is the command i've been doing: `conda-lock -k explicit --file environment.yml -p linux-64`

after that, can you also test the building of dockerfile? i've updated it to reflect how it is in the instructions in the individual milestone since python=3.11.7 now.

i deleted my previous branch, so the pull request was gone. this is my new branch. sorry for any inconvenience!

### CODE REVIEW

**Review by Psingh238 — COMMENTED** [review]
Changes look good to me.

**Comment by Psingh238** [comment]
> can someone please help with creating conda-lock? i'm unable to do it today with the way i previously did it and how i did it in my individual milestone. it's giving me an error but i'm not understanding it.
> 
> this is the command i've been doing: `conda-lock -k explicit --file environment.yml -p linux-64`
> 
> after that, can you also test the building of dockerfile? i've updated it to reflect how it is in the instructions in the individual milestone since python=3.11.7 now.
> 
> i deleted my previous branch, so the pull request was gone. this is my new branch. sorry for any inconvenience!

Can you post the error you get as a fenced code block please? I will take a look at that. In the meantime, I will pull your branch and try running the command myself.

**Comment by musiccabin** [comment]
I can't get to my laptop until 1.30 or 2pm. Can you try pulling my branch and run `conda-lock -k explicit --file environment.yml -p linux-64`?

My error takes up more than a full screen on my terminal. I always just ran that command with no problem though.

**Comment by Psingh238** [comment]
I did try running the command and I got an ImportError which I searched and found is due to the mamba version not working with the conda version which got updated. I am currently trying to implement a solution and I will let you know if it works.

**Comment by musiccabin** [comment]
Ok, ty! It's weird coz if we're using the same conda version as before, it should work... thx for your help!!!

**Comment by Psingh238** [comment]
For me, my conda version automatically updated to version 24.11.0 for some reason while my mamba was not updated. The suggested update is to update the mamba version in the base environment to something greater than 1.5.9. Check the conda version using `conda --version` and run `conda install mamba=1.5.9` if the conda version >= 24.0.0. Should fix the issue.

**Comment by Psingh238** [comment]
This is the [GitHub Issue](https://github.com/mamba-org/mamba/issues/3520) where I learnt about this issue and its fix from. If others have issue with mamba, then they can check it out.

**Comment by Psingh238** [comment]
I ran the command and I was able to build the image now. However, I see an issue with the pip modules not showing up in the Docker image. I will raise a different issue for this.

**Comment by sgdkd** [comment]
Hi, I‘ve read issue #42 , I wonder if you guys will update this pull request?

**Comment by Psingh238** [comment]
@sgdkd Issue #42 is almost addressed and will be completely resolved after I update the `environment.yml` file.

**Comment by Psingh238** [comment]
Should I also create the conda-lock file while I am at it?

**Comment by Psingh238** [comment]
Hold on, I realized that deepchecks is not used so I will remove that. Should also fix issue with version mismatch.

**Comment by sgdkd** [comment]
> Hold on, I realized that deepchecks is not used so I will remove that. Should also fix issue with version mismatch.

image
deepchecks is used

**Comment by Psingh238** [comment]
Oh okay, I didn't see that at the top of the imports. I will figure out something to fix the version mismatch then.

**Comment by Psingh238** [comment]
Okay, all changes are made now. I ran it and everything was working now but you can also check it out to make sure it runs correctly.

**Pull request merged**
